### ISSUE TITLE
Change default to always ignore flaky tests

### ISSUE THREAD

**Issue by nicoddemus** [coherent-oss/pytest-ignore-flaky#1]
Hi!

I like the idea of this plugin specially in light of the discussion going on in pytest-dev/pytest#814, but I think the default for the plugin should be to always ignore flaky tests, unless a explicit flag is passed (like `--fail-flaky` or `--run-flaky`), in which case tests marked as `flaky` that fail will fail the entire test run.

My reasoning is that once a project declares `pytest-ignore-flaky` as a dependency and marks some tests as `flaky`, it is understood that a few of those tests might fail. Project users and contributors usually expect to run `py.test` and see all tests pass, but in this case when a flaky test fails they would have to know that `pytest-ignore-flaky` is a dependency and that some of the tests are flaky so they have to pass `--ignore-flaky` in the command line to see that everything is OK with their installation or PR. 

Of course this can be mitigated by adding `addopts = --ignore-flaky` to `pytest.ini` or even by documentation how the tests are expected to run, but I feel the default should be to ignore flaky tests out-of-the box if the plugin is installed.

Hope my explanation makes sense! :smile:

Cheers,

**Comment by schettino72** [comment]
Thanks for your comment. Sure, your explanation makes sense, but...

I would like to keep the default as conservative as possible, so no one gets bitten by this.

For example, one of my project's tests works just fine on my own machine but is flaky on travis. So although I am likely to have `pytest-ignore-flaky` in my environment I wont use while working on my machine. I will use it just on travis.

Another problem of being enabled by default is that not everyone uses a single virtualenv for each project (or use virtualenv at all). This kind of people could be caught by surprise.

**Comment by nicoddemus** [comment]
No problem, thanks for the discussion! I can see the reasoning behind both approaches. :smile:

Cheers
:beers:

**Comment by schettino72** [comment]
Tranquilo Bruno, valeu ;)

**Comment by nicoddemus** [comment]
Valeu! :wink:
