### ISSUE TITLE
Switch default branch to main

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/pytest-ignore-flaky#10]
I'd like to switch the default branch for this project to `main`, to align with best practices and other projects.

@schettino72 Would you mind giving me owner or manager access to the repo so I can make this change?

**Comment by schettino72** [comment]
I guess it is not possible on repos that do not belong to an organization...

is there still an org for pytest plugins? if yes and you have access to it i can transfer this repository to that org.
Or you just fork it in whatever org and we put a note here saying this is not the MAIN/OFFICIAL repository anymore.

**Comment by jaraco** [comment]
I see. There are a couple of options.

Yes, some plugins are hosted with the [pytest-dev](/pytest-dev) org (the same one that hosts pytest). I'm not a manager of that org, so we'd need to contact someone there if you want to go that route.

Another option is to transfer to [Coherent-OSS](/coherent-oss). This is an org I formed recently with a fellow dev to host projects we manage but also small projects looking for a friendly, flexible home. I have plans to my my pytest plugins there. Transferring to Coherent doesn't have to be permanent - if you decide it's not a good home, I'll happily facilitate the transfer somewhere else. We're still developing the policy, so for now it's an ad hoc org.

I have a slight preference for Coherent, but it's up to you. If you want to initiate the transfer to Coherent, we could do that today. If you're thinking pytest-dev, I'll offer to reach out to the org managers to confirm their interest and any requirements they would have.

**Comment by schettino72** [comment]
> I have a slight preference for Coherent

You can do as you wish.

**Comment by jaraco** [comment]
In that case, please initiate the transfer to coherent-oss, and I'll take it from there. Thanks!

**Comment by schettino72** [comment]
I tried it but got the error message:

"You don’t have the permission to create public repositories on coherent-oss"

**Comment by jaraco** [comment]
Oh, interesting. I didn't realize you had to have that permission to transfer. Please bear with me as I learn how to use GitHub ;)

I've added you as a member of the org, which according to the settings should give you the ability to create repositories within the org, and thus should give you the ability to transfer the repo there. Please try again. Thanks.

**Comment by jaraco** [comment]
Thanks for transferring the repo. I've now renamed the default branch to `main` using the GitHub settings. Please update your clones to match (easiest way is to make sure you don't have any local branches and then re-clone).
