### ISSUE TITLE
Interaction with rerunfailures-7.0 causing problems

### ISSUE THREAD

**Issue by jpadhye** [coherent-oss/pytest-ignore-flaky#3]
rerunfailures-7.0 also has the same marker. I'm using `@pytest.mark.flaky(reruns=3, reruns_delay=60` . The test failure is ignored without without any reruns. Can the plugin be modified to allow reruns or change the marker to `pytest.mark.ignore_flaky`?

**Comment by schettino72** [comment]
I guess it would make more sense for "rerunfailures" to use a marker name related to their name...
Also not clear to me the problem is caused is caused by this project.
