### ISSUE TITLE
Why not enabled by default?

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/pytest-ignore-flaky#5]
It takes three actions to use this library:

- install the plugin
- run pytest with the plugin enabled
- have some tests marked flaky

That seems like overkill for such a simple workflow. Why not eliminate the middle step and leave the plugin enabled unconditionally (if installed)? If there are no tests marked flaky, it will have no effect, and if there are tests marked flaky, the user probably intended for the plugin to be enabled. Additionally, the user can disable the plugin when installed with `-p no:ignore_flaky`.

It doesn't affect me too much, as I use [pytest-enabler](/jaraco/pytest-enabler) to supply "reasonable default" options for all the plugins, but if this plugin were to run by default, it would simplify the implementation of pytest-enabler, simplify the getting-started docs, and simplify the code itself.

**Comment by schettino72** [comment]
Yes, I want to be very conservative and explicit about using this plugin... 

My reasoning was that this plugin to be enabled only when run by CI.

Maybe a questionable but since it is configurable I would not like to change this.
