### ISSUE TITLE
Maintenance plan?

### ISSUE THREAD

**Issue by jaraco** [coherent-oss/pytest-ignore-flaky#7]
Is this project maintained? If not, would you consider handing off maintenance to someone willing to address issues?

I'm willing to help maintain it. Just give me ownership access to the project in PyPI and I can do the rest. You may also transfer this repo to me to maintain continuity of tracked issues.

I'd be happy to share custody or for the original author to retain custody, but I'd really like to see the issues addressed.

**Comment by schettino72** [comment]
sorry for the delay. I have added you as co-maintainer here and on pypi.
Let me know if you need any other access.
